export const sideBarLinks = [
    {
        name: 'Dashboard',
        link: '/',
        icon:'/icons/dashboard.svg'
    },
    {
        name: 'Vacancies',
        link: '/vacancies',
        icon:'/icons/vacancies.svg'
    },
    {
        name: 'Applicants',
        link: '/applicants',
        icon:'/icons/user.svg'
    },
    {
        name: 'Employees',
        link: '/employees',
        icon:'/icons/employee.svg'
    },
    {
        name: 'Payroll',
        link: '/payroll',
        icon:'/icons/payroll.svg'
    },

];

export const empTypes = [
    {title:"Full Time",value:'fulltime'},
    {title:"Part Time",value:'parttime'},
    {title:"Contract",value:'contract'},
    {title:'Freelance',value:"freelance"},
    {title:"Remote",value:'remote'}
];
export const JobStatus = [
    'inprogress',
    'active',
    'pending',
    'completed'
] 

export const jobSuitbleFor =[
    {title:"All",value:"all"},
    {title:"Student",value:"student"},
    {title:"Veteran",value:"veteran"},
    {title:"Person With Disabilities",value:"person_with_disability"},
    {title:"Experienced",value:"experienced"}
];
export const SalaryOptions = {
    currecyList :[
        "INR",
        "EUR",
        "USD"
    ],
    perTime:[
        'hourly',
        'monthly',
        'anually'
    ]
}

export const departments = [
    "Software Development",
    "Quality Assurance",
    "Human Resources",
    "Finance",
    "Customer Support",
    "IT Support",
    "Product Management",
    "Sales",
    "Marketing",
    "Operations",
    "Research and Development",
    "Project Management",
    "DevOps",
    "Data Science",
    "Security",
    "Network Engineering",
    "Technical Writing",
    "Design",
    "Business Analysis",
    "Legal"
  ];

export const positions = [
    "Software Engineer",
    "Senior Software Engineer",
    "Lead Developer",
    "Quality Assurance Engineer",
    "QA Lead",
    "Project Manager",
    "Product Manager",
    "Data Scientist",
    "Data Analyst",
    "DevOps Engineer",
    "System Administrator",
    "Network Engineer",
    "Security Analyst",
    "Technical Writer",
    "UI/UX Designer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "IT Support Specialist",
    "Business Analyst",
    "Human Resources Manager",
    "Finance Manager",
    "Marketing Specialist",
    "Sales Executive",
    "Customer Support Representative",
    "Research Scientist",
    "Legal Advisor"
  ];

export  const AllSkills =  [
    "JavaScript",
    "HTML",
    "CSS",
    "React",
    "Node.js",
    "Python",
    "Java",
    "SQL",
    "Git",
    "Agile methodologies",
    "TypeScript",
    "Spring Boot",
    "Microservices",
    "AWS",
    "Docker",
    "Kubernetes",
    "CI/CD",
    "Project management",
    "Scrum",
    "JIRA",
    "Confluence",
    "Team leadership",
    "Risk management",
    "Budgeting",
    "Stakeholder management",
    "Communication",
    "Test planning",
    "Test automation",
    "Selenium",
    "JUnit",
    "TestNG",
    "Cypress",
    "Postman",
    "API testing",
    "Performance testing",
    "Bug tracking",
    "Azure",
    "Google Cloud",
    "Jenkins",
    "Terraform",
    "Ansible",
    "Monitoring and logging",
    "Scripting (Bash, Python)",
    "User research",
    "Wireframing",
    "Prototyping",
    "Adobe XD",
    "Figma",
    "Sketch",
    "User testing",
    "Responsive design",
    "Design systems",
    "R",
    "Machine learning",
    "Deep learning",
    "Data visualization",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "TensorFlow",
    "Keras",
    "Big data technologies",
    "Data analysis",
    "Systems analysis",
    "Requirements gathering",
    "Business analysis",
    "UML",
    "Data modeling",
    "Problem-solving",
    "Network design",
    "Network security",
    "Cisco technologies",
    "Firewalls",
    "VPN",
    "Routing and switching",
    "Wireless networking",
    "Troubleshooting",
    "Network monitoring",
    "Database design",
    "Oracle",
    "MySQL",
    "PostgreSQL",
    "Database security",
    "Performance tuning",
    "Backup and recovery",
    "Data migration",
    "Communication",
    "Teamwork",
    "Adaptability",
    "Problem-solving",
    "Creativity",
    "Work ethic",
    "Interpersonal skills",
    "Time management",
    "Attention to detail",
    "Emotional intelligence",
    "Conflict resolution",
    "Critical thinking",
    "Decision-making",
    "Leadership",
    "Motivation",
    "Negotiation",
    "Presentation skills",
    "Resilience",
    "Stress management"
  ];