import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider 
    appearance={{
      layout: {
        logoImageUrl: '/icons/logo.svg',
        socialButtonsVariant: 'iconButton'
      },
      variables: {
        colorText: '#0d0d0d',
        colorPrimary: '#0e78f9',
        colorBackground: '#fbfbfb',
        colorInputBackground: '#f9f9f9',
        colorInputText: '#fff'
      }
    }}
    >
    <html lang="en"> 
      <body className={inter.className}>{children}</body>
    </html>
    </ClerkProvider>
  );
}
